<?php

return [
      'PERSATUAN MAHASISWA UNIVERSITI KEBANGSAAN MALAYSIA', 
      'PERTUBUHAN AKADEMIK FAKULTI', 
      'PERTUBUHAN ANAK NEGERI/KEBAJIKAN', 
      'PERTUBUHAN KEBAJIKAN KOLEJ', 
      'PERTUBUHAN KHUSUS', 
      'PERTUBUHAN LUAR', 
      'PERTUBUHAN SISWAZAH', 
      'PUSAT KEMBANGAN PENDIDIKAN', 
      'URUSETIA HEPA'
];